export const SKILLS = {
  samurai: [
    {
      id: "blade-dash",
      name: "Blade Dash",
      description: "Dash forward in a line, slashing every enemy in your path.",
      type: "active",
      cooldown: 4,
      mpCost: 15,
      damage: 2.5,
      effect: null,
      animation: "slash",
      icon: "⚡",
    },
    {
      id: "fury-strike",
      name: "Fury Strike",
      description: "Unload 5 rapid strikes in 1 second. Each hits for 60% weapon damage.",
      type: "active",
      cooldown: 8,
      mpCost: 25,
      damage: 3.0,
      effect: "bleed",
      animation: "slash",
      icon: "🔥",
    },
    {
      id: "parry",
      name: "Parry",
      description: "Passive: 20% chance to deflect incoming attacks and counter for 150% damage.",
      type: "passive",
      cooldown: 0,
      mpCost: 0,
      damage: 1.5,
      effect: "counter",
      animation: "slash",
      icon: "🛡️",
    },
    {
      id: "cyber-katana-combo",
      name: "Cyber Katana Combo",
      description: "Unleash a 3-hit combo ending in a massive downward slash. Stuns target for 1.5s.",
      type: "active",
      cooldown: 15,
      mpCost: 40,
      damage: 5.0,
      effect: "stun",
      animation: "slash",
      icon: "⚔️",
    },
  ],

  netrunner: [
    {
      id: "system-hack",
      name: "System Hack",
      description: "Remotely hack an enemy's augments, reducing their damage by 40% for 5s.",
      type: "active",
      cooldown: 6,
      mpCost: 20,
      damage: 1.0,
      effect: "weaken",
      animation: "hack",
      icon: "💻",
    },
    {
      id: "firewall",
      name: "Firewall",
      description: "Erect a data firewall around yourself, absorbing the next 3 hits.",
      type: "active",
      cooldown: 12,
      mpCost: 30,
      damage: 0,
      effect: "shield",
      animation: "hack",
      icon: "🔒",
    },
    {
      id: "data-bomb",
      name: "Data Bomb",
      description: "Launch a compressed exploit packet that detonates on contact for massive AoE damage.",
      type: "active",
      cooldown: 10,
      mpCost: 35,
      damage: 4.0,
      effect: "silence",
      animation: "hack",
      icon: "💣",
    },
    {
      id: "neural-override",
      name: "Neural Override",
      description: "Seize control of an enemy's nervous system for 4s, turning them against their allies.",
      type: "active",
      cooldown: 20,
      mpCost: 50,
      damage: 0,
      effect: "charm",
      animation: "hack",
      icon: "🧠",
    },
  ],

  infiltrator: [
    {
      id: "shadow-step",
      name: "Shadow Step",
      description: "Instantly teleport behind your target, invisible for 1s afterward.",
      type: "active",
      cooldown: 5,
      mpCost: 18,
      damage: 0,
      effect: "invisible",
      animation: "stealth",
      icon: "👤",
    },
    {
      id: "backstab",
      name: "Backstab",
      description: "Strike from behind for 350% weapon damage. Always crits from stealth.",
      type: "active",
      cooldown: 7,
      mpCost: 22,
      damage: 3.5,
      effect: "poison",
      animation: "stealth",
      icon: "🗡️",
    },
    {
      id: "smoke-screen",
      name: "Smoke Screen",
      description: "Deploy a smoke canister that blinds all enemies in a 5m radius for 3s.",
      type: "active",
      cooldown: 14,
      mpCost: 28,
      damage: 0,
      effect: "blind",
      animation: "stealth",
      icon: "💨",
    },
    {
      id: "assassinate",
      name: "Assassinate",
      description: "Instant-kill any enemy below 25% HP. On bosses, deals 800% weapon damage instead.",
      type: "active",
      cooldown: 25,
      mpCost: 60,
      damage: 8.0,
      effect: "execute",
      animation: "stealth",
      icon: "💀",
    },
  ],

  shaman: [
    {
      id: "river-surge",
      name: "River Surge",
      description: "Call a surge of Willamette river energy, knocking back all nearby enemies.",
      type: "active",
      cooldown: 6,
      mpCost: 20,
      damage: 2.0,
      effect: "knockback",
      animation: "aoe",
      icon: "🌊",
    },
    {
      id: "nature-bind",
      name: "Nature Bind",
      description: "Entangle an enemy in roots for 3 seconds, preventing movement.",
      type: "active",
      cooldown: 8,
      mpCost: 22,
      damage: 1.0,
      effect: "root",
      animation: "aoe",
      icon: "🌿",
    },
    {
      id: "heal",
      name: "Spirit Heal",
      description: "Channel forest energy to restore 30% of max HP over 3 seconds.",
      type: "active",
      cooldown: 18,
      mpCost: 35,
      damage: -0.3, // negative = heal
      effect: "regen",
      animation: "beam",
      icon: "💚",
    },
    {
      id: "elemental-storm",
      name: "Elemental Storm",
      description: "Summon a massive storm of water, lightning, and root energy that devastates an area for 5s.",
      type: "active",
      cooldown: 30,
      mpCost: 70,
      damage: 6.0,
      effect: "stun",
      animation: "aoe",
      icon: "⛈️",
    },
  ],
};
